jobboard/config/routes.rb
Rails.application.routes.draw do
  resources :targets
  post '/users/admin_edit', to: 'users#admin_edit'
  post '/offers/:id/close', to: 'offers#close'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/offers/filter', to: 'offers#filter'
  resources :applications
  resources :offers
  resources :companies
  resources :users

  root 'offers#index'

end

jobboard/app/models/target.rb
class Target < ActiveRecord::Base
    has_many :offers
end

jobboard/app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:label)
    end
end

jobboard/app/helpers/targets_helper.rb
module TargetsHelper
end

jobboard/app/views/targets/_form.html.haml
= form_for @target do |f|
  - if @target.errors.any?
    #error_explanation
      %h2= "#{pluralize(@target.errors.count, "error")} prohibited this target from being saved:"
      %ul
        - @target.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :label
    = f.text_field :label
  .actions
    = f.submit 'Save'

jobboard/app/views/targets/edit.html.haml
%h1 Editing target

= render 'form'

= link_to 'Show', @target
\|
= link_to 'Back', targets_path

jobboard/app/views/targets/index.html.haml
%h1 Listing targets

%table
  %thead
    %tr
      %th Label
      %th
      %th
      %th

  %tbody
    - @targets.each do |target|
      %tr
        %td= target.label
        %td= link_to 'Show', target
        %td= link_to 'Edit', edit_target_path(target)
        %td= link_to 'Destroy', target, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Target', new_target_path

jobboard/app/views/targets/new.html.haml
%h1 New target

= render 'form'

= link_to 'Back', targets_path

jobboard/app/views/targets/show.html.haml
%p#notice= notice

%p
  %b Label:
  = @target.label

= link_to 'Edit', edit_target_path(@target)
\|
= link_to 'Back', targets_path