jobboard/config/routes.rb
Rails.application.routes.draw do
  resources :targets
  post '/users/admin_edit', to: 'users#admin_edit'
  post '/offers/:id/close', to: 'offers#close'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/offers/filter', to: 'offers#filter'
  resources :applications
  resources :offers
  resources :companies
  resources :users

  root 'offers#index'

end

jobboard/app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  has_many :applications
  has_one :target
  
  validates :start_date, presence: true
  validates :duration, presence: true
  validates :title, presence: true
end

jobboard/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.where(published: true)
    @offers_not_published = Offer.where(published: false)
  end

  def filter
    @filter_company_id = params[:filter_company_id]
    @filter_target_id = params[:filter_target_id]
    @offers_not_published = Offer.where(published: false)
    conditions = {published: true}
    if @filter_company_id.present?
        conditions[:company_id] = @filter_company_id
    end
    if @filter_target_id.present?
        conditions[:target_id] = @filter_target_id
    end
    @offers = Offer.where(conditions)
    respond_to do |format|
      format.html { render :index }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end


  def close


    @offer.active = false;
    @offer.save()
  end

  # GET /offers/new
  def new
    authorize! :create, Offer

    @offer = Offer.new
    @companies = Company.all
  end

  # GET /offers/1/edit
  def edit
    authorize! :edit, @offer

    @companies = Company.all
  end

  # POST /offers
  # POST /offers.json
  def create
    authorize! :create, Offer

    offer_params[:user_id] = current_user.id
    @offer = Offer.new(offer_params)

    notice = "L'offre a été créée."
    if !(can? :publish, Offer)
      @offer.published = false
      notice = "L'offre a été créée et à été soumise à validation."
    end

    @offer.user_id = current_user.id

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: notice }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    authorize! :destroy, Offer
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:company_id, :title, :target_id, :description, :duration, :creation_date, :start_date, :expiration_date, :contact, :category_id, :active, :published)
    end
end

jobboard/app/helpers/offers_helper.rb
module OffersHelper
end

jobboard/app/views/offers/_form.html.haml
= form_for @offer, :html => {:class => "form-horizontal"} do |f|
  - if @offer.errors.any?
    #error_explanation
      %h2
        = pluralize(@offer.errors.count, "error")
        prohibited this offer from being saved:
      %ul
        - @offer.errors.full_messages.each do |message|
          %li= message
  .panel.login-panel
    .panel-body
      .form-group
        %label.col-sm-2.control-label{:for => "company"} Entreprise
        .col-sm-10
          .input-group
            = f.collection_select :company_id, Company.all, :id, :name, {}, {:class => "form-control"}
            %span.input-group-btn
              %a.btn.btn-default.plus_button{:href => '/companies/new'} +
      .form-group
        %label.col-sm-2.control-label{:for => "offer_title"} Intitulé
        .col-sm-10
          = f.text_field :title, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "offer_target"} Etudiants ciblés
        .col-sm-10
          = f.collection_select :target_id, Target.all, :id, :label, {}, {:class => "form-control"}
      .form-group
        %label.col-sm-2.control-label{:for => "offer_description"} Description
        .col-sm-10
          = f.text_area :description, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "offer_duration"} Durée en semaines
        .col-sm-10
          = f.number_field :duration, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "offer_start_date"} Du
        .col-sm-10
          = f.date_field :start_date, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "offer_expiration_date"} Au
        .col-sm-10
          = f.date_field :expiration_date, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "offer_contact"} Adresse e-mail de contact
        .col-sm-10
          = f.email_field :contact, :class => "form-control"
      - if can? :publish, Offer
        .form-group
          %label.col-sm-2.control-label{:for => "offer_published"} Publiée
          .col-sm-10
            = f.check_box :published, :class => "form-control"
      .form_group
        .col-sm-2
        .col-sm-10
          = f.submit "Envoyer", :class => "btn btn-default"

jobboard/app/views/offers/edit.html.haml
%h1 Edition de l'offre
= render 'form'

jobboard/app/views/offers/index.html.haml
%h1 Les offres actuelles

.panel.panel-default
  .panel-heading Filtrer
  .panel-body
    .row
      %form{:action => '/offers/filter'}
        .col-md-4
          = select_tag "filter_company_id", options_from_collection_for_select(Company.all, "id", "name", @filter_company_id), :include_blank => 'Toutes les entreprises', :class => "form-control"
        .col-md-4
          = select_tag "filter_target_id", options_from_collection_for_select(Target.all, "id", "label", @filter_target_id), :include_blank => 'Tout type', :class => "form-control"
        .col-md-4
          %input.btn.btn-default{:type => 'submit'}

.list-group
- @offers.each do |offer|
  %a.list-group-item.smooth{:href => "/offers/#{offer.id}"}
    %h4.list-group-item-heading= offer.title
    %p.list-group-item-text= " de " + offer.company.name + " - à partir du " + offer.start_date.strftime("%d/%m/%Y")
- if @offers.count == 0
  .list-group-item.smooth
    %h4.list-group-item-heading.lastBox Aucune offre ne correspond à votre recherche
    %p.list-group-item-text

- if can? :publish, Offer
  %h1 Offres en attente de validation
  .list-group
  - @offers_not_published.each do |offer|
    %a.list-group-item.smooth{:href => "/offers/#{offer.id}/edit"}
      %h4.list-group-item-heading= offer.title
      %p.list-group-item-text= " de " + offer.company.name + " - à partir du " + offer.start_date.strftime("%d/%m/%Y")
  - if @offers_not_published.count == 0
    .list-group-item.smooth
      %h4.list-group-item-heading.lastBox Aucune offre n'est en attente de validation
      %p.list-group-item-text


%br

  .right-button-container
    - if can? :show, Company
      %a{:href => "/companies"}
        %button.btn.btn-primary.btn-lg Liste des entreprises
    - if can? :create, Offer
      %a{:href => "/users"}
        %button.btn.btn-primary.btn-lg Liste des utilisateurs
    - if can? :create, Offer
      %a{:href => "/offers/new"}
        %button.btn.btn-primary.btn-lg Proposer une offre
%br

jobboard/app/views/offers/new.html.haml
%h1 Proposer une offre
= render 'form'

jobboard/app/views/offers/show.html.haml
%h1= @offer.title
.panel.panel-default
  .panel-body
    %h3.display-offer
      De
      %a{:href => "/companies/#{@offer.company.id}"}
        = @offer.company.name
      -
      = @offer.created_at.strftime("%d/%m/%Y")
    %p= @offer.description
    %strong= "A partir du "+@offer.start_date.strftime("%d/%m/%Y")+" pour une durée de #{@offer.duration} semaines"
    - if can? :apply, Offer
      .right-button-container.lastBox
        %a{:href => "mailto:#{@offer.contact}?subject=#{@offer.title}"}
          %button.btn.btn-primary.btn-lg Postuler
    %br
    - if can? :close, Offer
      = button_to "Fermer cette annonce", offer_path(:id => @offer.id), :method => :delete, :class => "btn btn-default"
    %br
    - if can? :edit, @offer
      = button_to "Editer cette annonce", edit_offer_path(:id => @offer.id), :method => :get, :class => "btn btn-default"
%a{:href => "/"}
  %button.btn.btn-default Retour