jobboard/config/routes.rb
Rails.application.routes.draw do
  resources :targets
  post '/users/admin_edit', to: 'users#admin_edit'
  post '/offers/:id/close', to: 'offers#close'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/offers/filter', to: 'offers#filter'
  resources :applications
  resources :offers
  resources :companies
  resources :users

  root 'offers#index'

end

jobboard/app/models/company.rb
class Company < ActiveRecord::Base
  has_one :user
  has_many :offers

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :mail, presence: true
end

jobboard/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    authorize! :edit, @company
  end

  # POST /companies
  # POST /companies.json
  def create
    authorize! :create, @company

    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :mail, :phone, :address, :description)
    end
end

jobboard/app/helpers/companies_helper.rb
module CompaniesHelper
end

jobboard/app/views/companies/_form.html.haml
= form_for @company, :html => {:class => "form-horizontal"} do |f|
  - if @company.errors.any?
    #error_explanation
      %h2
        = pluralize(@company.errors.count, "error")
        prohibited this offer from being saved:
      %ul
        - @company.errors.full_messages.each do |message|
          %li= message
  .panel.login-panel
    .panel-body
      .form-group
        %label.col-sm-2.control-label{:for => "company_name"} Nom de l'entreprise
        .col-sm-10
          = f.text_field :name, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "company_description"} Description
        .col-sm-10
          = f.text_area :description, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "company_phone"} Téléphone
        .col-sm-10
          = f.text_field :phone, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "company_mail"} Adresse email
        .col-sm-10
          = f.text_field :mail, :class => "form-control"
      .form-group
        %label.col-sm-2.control-label{:for => "company_address"} Adresse
        .col-sm-10
          = f.text_area :address, :class => "form-control"
      .form_group
        .col-sm-2
        .col-sm-10
          = f.submit "Envoyer", :class => "btn btn-default"

jobboard/app/views/companies/edit.html.haml
%h1 Editing Company
= render 'form'
= link_to 'Show', @company
|
= link_to 'Back', companies_path

jobboard/app/views/companies/index.html.haml
%h1 Entreprises

.list-group
- @companies.each do |company|
  %a.list-group-item.smooth{:href => "/companies/#{company.id}"}
    %h4.list-group-item-heading= company.name
    %p.list-group-item-text=  company.address
- if @companies.count == 0
  .list-group-item.smooth
    %h4.list-group-item-heading.lastBox Il n'y a aucun entreprise.
    %p.list-group-item-text

.right-button-container
  - if can? :create, Company
    %a{:href => "/companies/new"}
      %button.btn.btn-primary.btn-lg Ajouter une entreprise
%br/

jobboard/app/views/companies/new.html.haml
%h1 Nouvelle entreprise
= render 'form'

jobboard/app/views/companies/show.html.haml
%h1= @company.name
.panel.login-panel
  .panel-body
    %p= @company.description
    %h2.companyTitle Coordonnées
    %ul
      %li= "Téléphone : " + @company.phone
      %li= "Adresse : " + @company.address
    %div{:id => 'map-canvas'}

    %iframe{:src => "https://www.google.com/maps/embed/v1/place?q=#{@company.address}%2C%20France&key=AIzaSyBCAYpl39PffuO98h834z-hVfMIqGQ7hUc", :style => 'border:0'}

    - if can? :edit, @company
      = button_to "Editer cette entreprise", edit_company_path(:id => @company.id), :method => :get, :class => "btn btn-default"